import test from 'node:test'; import assert from 'node:assert/strict';
import { evaluateDemoPlan, fallbackPlan, normalizeProposal, validateProposal } from './ai-policy.mjs';

test('nested allocations reserve budget and leave a deterministic remainder', () => { const plan = fallbackPlan('research', 5); const result = evaluateDemoPlan(plan, 5); assert.equal(result.valid, true); assert.equal(result.reserved, 3.5); assert.equal(result.spent, 0.2); assert.equal(result.remaining, 1.3); });
test('allowlist rejects an unknown service category', () => { const plan = fallbackPlan('research', 5); plan.services.push({ category: 'wallet-drain', estimatedCost: 0, description: 'invalid' }); const result = evaluateDemoPlan(plan, 5); assert.equal(result.valid, false); assert.match(result.errors.join(' '), /not allowed/); });
test('STOP propagation blocks queued descendants', () => { const result = evaluateDemoPlan(fallbackPlan('research', 5), 5, { revoked: true }); assert.equal(result.valid, false); assert.match(result.blockedActions.join(' '), /STOP propagated/); assert.ok(result.decisions.every((item) => item.status === 'blocked')); });
test('over-budget model proposal is rejected before execution', () => { const plan = fallbackPlan('research', 5); plan.rootAgent.budget = 6; const result = validateProposal(plan, 5); assert.equal(result.valid, false); assert.match(result.errors.join(' '), /exceeds/); });
test('scope, expiry, depth, recipient, and replay checks are deterministic', () => { const plan = fallbackPlan('research', 5); plan.subAgents[0].scope = ['wallet-drain']; plan.subAgents[0].expiry = new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(); plan.subAgents[0].delegationDepth = 2; plan.services[0].requestId = 'req-1'; plan.services.push({ category: 'research', description: 'replay', estimatedCost: 0, requestId: 'req-1', sender: '0xabc', recipient: '0xabc' }); const result = validateProposal(plan, 5); assert.match(result.errors.join(' '), /widen|extends|depth|replay|distinct/); });
test('normalizes relative expiry to a future child deadline bounded by the task', () => { const now = Date.parse('2026-01-01T00:00:00.000Z'); const plan = normalizeProposal({ taskSummary: 'Research', rootAgent: { role: 'Coordinator', budget: 5 }, needsSubAgents: true, subAgents: [{ role: 'Researcher', budget: 1, scope: ['research'], relativeExpiryHours: 48, delegationDepth: 1 }], services: [{ category: 'research', description: 'Search', estimatedCost: 0.2 }], finalOutputType: 'report' }, { goal: 'Research', now }); const result = validateProposal(plan, 5, { now, allowedScope: new Set(['research']) }); assert.equal(result.valid, true); assert.equal(plan.expiry, '2026-01-02T00:00:00.000Z'); assert.equal(plan.subAgents[0].expiry, plan.expiry); });
test('child scope must be a subset of the proposal service categories', () => { const plan = fallbackPlan('research', 5); plan.subAgents[0].scope = ['api']; const result = validateProposal(plan, 5, { allowedScope: new Set(['research', 'data']) }); assert.equal(result.valid, false); assert.match(result.errors.join(' '), /widen/); });
