import test from 'node:test'; import assert from 'node:assert/strict';
import { handleOrchestration } from './orchestrate.mjs';

const request = (body, headers = {}) => new Request('http://localhost/api/orchestrate', { method: 'POST', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify(body) });
const valid = { taskSummary: 'Research', rootAgent: { role: 'Coordinator', budget: 5 }, needsSubAgents: false, subAgents: [], services: [{ category: 'research', description: 'Search', estimatedCost: 0.2 }], finalOutputType: 'report', expiry: new Date(Date.now() + 86_400_000).toISOString() };
test('missing key returns labeled fallback', async () => { const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }), { env: {}, now: () => 1 }); assert.equal(result.status, 200); assert.equal((await result.json()).source, 'fallback'); });
test('valid structured output is accepted', async () => { const body = await (await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'valid-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 100, fetchImpl: async () => new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: JSON.stringify(valid) }] } }] }), { status: 200 }) })).json(); assert.equal(body.source, 'gemini'); });
test('malformed provider output falls back', async () => { const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'malformed-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 200, fetchImpl: async () => new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: '{bad' }] } }] }), { status: 200 }) }); assert.equal((await result.json()).source, 'fallback'); });
test('provider quota exhaustion falls back', async () => { const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'quota-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 300, fetchImpl: async () => new Response('{}', { status: 429 }) }); const body = await result.json(); assert.equal(body.source, 'fallback'); assert.match(body.reason, /quota/); });
test('default model retries with compatibility model after a 404', async () => { let calls = 0; const body = await (await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'compatibility-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 400, fetchImpl: async (url) => { calls += 1; if (url.includes('gemini-2.5-flash-lite')) return new Response('{}', { status: 404 }); return new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: JSON.stringify(valid) }] } }] }), { status: 200 }); } })).json(); assert.equal(calls, 2); assert.equal(body.source, 'gemini'); assert.equal(body.model, 'gemini-2.5-flash'); });
test('invalid request is rejected', async () => { const result = await handleOrchestration(request({ goal: '', budget: 0 }), { env: {}, now: () => 400 }); assert.equal(result.status, 400); });
