import test from 'node:test'; import assert from 'node:assert/strict';
import { GEMINI_API_VERSION, geminiEndpoint, handleOrchestration } from './orchestrate.mjs';

const request = (body, headers = {}) => new Request('http://localhost/api/orchestrate', { method: 'POST', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify(body) });
const valid = { taskSummary: 'Research', rootAgent: { role: 'Coordinator', budget: 5 }, needsSubAgents: false, subAgents: [], services: [{ category: 'research', description: 'Search', estimatedCost: 0.2 }], finalOutputType: 'report', expiry: new Date(Date.now() + 86_400_000).toISOString() };
test('missing key returns labeled fallback', async () => { const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }), { env: {}, now: () => 1 }); assert.equal(result.status, 200); assert.equal((await result.json()).source, 'fallback'); });
test('valid structured output is accepted', async () => { const body = await (await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'valid-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 100, fetchImpl: async () => new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: JSON.stringify(valid) }] } }] }), { status: 200 }) })).json(); assert.equal(body.source, 'gemini'); });
test('malformed provider output falls back', async () => { const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'malformed-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 200, fetchImpl: async () => new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: '{bad' }] } }] }), { status: 200 }) }); assert.equal((await result.json()).source, 'fallback'); });
test('provider quota exhaustion falls back', async () => { const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'quota-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 300, fetchImpl: async () => new Response('{}', { status: 429 }) }); const body = await result.json(); assert.equal(body.source, 'fallback'); assert.match(body.reason, /quota/); });
test('invalid request is rejected', async () => { const result = await handleOrchestration(request({ goal: '', budget: 0 }), { env: {}, now: () => 400 }); assert.equal(result.status, 400); });
test('builds the documented v1beta endpoint and encodes model names', () => { assert.equal(GEMINI_API_VERSION, 'v1beta'); assert.equal(geminiEndpoint('gemini-2.5-flash-lite'), 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent'); });
test('model override is used without fallback retry', async () => { let called; const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'override-test' }), { env: { GEMINI_API_KEY: 'test', GEMINI_MODEL: 'gemini-custom' }, now: () => 500, fetchImpl: async (url) => { called = url; return new Response(JSON.stringify({ error: { message: 'not found' } }), { status: 404 }); } }); const body = await result.json(); assert.equal(called, geminiEndpoint('gemini-custom')); assert.equal(body.source, 'fallback'); assert.equal(body.model, 'gemini-custom'); assert.equal(body.diagnostic.code, 404); assert.equal(body.diagnostic.message, 'not found'); assert.equal(body.diagnostic.version, 'v1beta'); });
test('malformed provider response is sanitized and falls back', async () => { const result = await handleOrchestration(request({ goal: 'Research Arc', budget: 5 }, { 'x-forwarded-for': 'malformed-provider-test' }), { env: { GEMINI_API_KEY: 'test' }, now: () => 600, fetchImpl: async () => new Response('upstream unavailable', { status: 502 }) }); const body = await result.json(); assert.equal(body.source, 'fallback'); assert.equal(body.diagnostic.code, 502); assert.equal(body.diagnostic.message, 'No provider message.'); });
